import test from "node:test";
import assert from "node:assert/strict";
import * as publicApi from "../../src/index.js";
import * as queryBuilders from "../../src/ydb-core/query-builders/index.js";
import { YdbDatabase } from "../../src/ydb-core/db.js";
import { YdbDeleteBuilder } from "../../src/ydb-core/query-builders/delete.js";
import { YdbInsertBuilder } from "../../src/ydb-core/query-builders/insert.js";
import { YdbRelationalQuery, YdbRelationalQueryBuilder } from "../../src/ydb-core/query-builders/query.js";
import { except, intersect, union, unionAll, YdbSelectBuilder } from "../../src/ydb-core/query-builders/select.js";
import { YdbUpdateBuilder } from "../../src/ydb-core/query-builders/update.js";
import { YdbSession } from "../../src/ydb-core/session.js";
import { YdbTransaction } from "../../src/ydb-core/transaction.js";
import { ydbTable } from "../../src/ydb-core/table.js";
import { buildCreateTableSql } from "../../src/ydb/migration-ddl.js";
import { migrate } from "../../src/ydb/migrator.js";
import { customType } from "../../src/ydb-core/columns/custom.js";
import { integer } from "../../src/ydb-core/columns/integer.js";
import { text } from "../../src/ydb-core/columns/text.js";
import { index, uniqueIndex } from "../../src/ydb-core/indexes.js";
import { primaryKey } from "../../src/ydb-core/primary-keys.js";
import { unique } from "../../src/ydb-core/unique-constraint.js";
import { YdbDialect } from "../../src/ydb/dialect.js";
import { drizzle, createDrizzle } from "../../src/ydb/createDrizzle.js";
import { YdbDriver } from "../../src/ydb/driver.js";

test("root public API re-exports runtime entry points", () => {
  assert.equal(publicApi.YdbDialect, YdbDialect);
  assert.equal(publicApi.YdbDriver, YdbDriver);
  assert.equal(publicApi.YdbSession, YdbSession);
  assert.equal(publicApi.YdbTransaction, YdbTransaction);
  assert.equal(publicApi.YdbDatabase, YdbDatabase);
  assert.equal(publicApi.drizzle, drizzle);
  assert.equal(publicApi.createDrizzle, createDrizzle);
  assert.equal(publicApi.ydbTable, ydbTable);
  assert.equal(publicApi.integer, integer);
  assert.equal(publicApi.int, integer);
  assert.equal(publicApi.text, text);
  assert.equal(publicApi.customType, customType);
  assert.equal(publicApi.index, index);
  assert.equal(publicApi.uniqueIndex, uniqueIndex);
  assert.equal(publicApi.primaryKey, primaryKey);
  assert.equal(publicApi.unique, unique);
  assert.equal(publicApi.buildCreateTableSql, buildCreateTableSql);
  assert.equal(publicApi.migrate, migrate);
  assert.equal(publicApi.union, union);
  assert.equal(publicApi.unionAll, unionAll);
  assert.equal(publicApi.intersect, intersect);
  assert.equal(publicApi.except, except);
});

test("query builder barrel re-exports concrete builder implementations", () => {
  assert.equal(queryBuilders.YdbSelectBuilder, YdbSelectBuilder);
  assert.equal(queryBuilders.YdbInsertBuilder, YdbInsertBuilder);
  assert.equal(queryBuilders.YdbUpdateBuilder, YdbUpdateBuilder);
  assert.equal(queryBuilders.YdbDeleteBuilder, YdbDeleteBuilder);
  assert.equal(queryBuilders.YdbRelationalQueryBuilder, YdbRelationalQueryBuilder);
  assert.equal(queryBuilders.YdbRelationalQuery, YdbRelationalQuery);
  assert.equal(queryBuilders.union, union);
  assert.equal(queryBuilders.unionAll, unionAll);
  assert.equal(queryBuilders.intersect, intersect);
  assert.equal(queryBuilders.except, except);
});
